---
image: python:3.10

stages:
  - test

lint:
  stage: test
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

test:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - pytest
