---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.269"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi
          - pydantic
          - motor-types
          - mongomock
          - beanie
          - web-poet
          - pytest
          - types-pytest-lazy-fixture
        args: ["--config", "pyproject.toml"]

    # I still need these checks, but it seems to me when commit is done
    # and pre-commit is launched, I care more about ruff & mypy in the first place,
    # but these are still important for non-code, configs, whitespaces etc.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # syntax check
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-symlinks
      # whitespaces
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      # scripts/exe
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # credentials leak
      - id: detect-private-key
      # python
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
