---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # syntax check
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-symlinks
      # whitespaces
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      # scripts/exe
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # credentials leak
      - id: detect-private-key
      # python
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.265"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.2.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi
          - pydantic
          - motor-types
          - beanie
          - web-poet
          - pytest
          - types-pytest-lazy-fixture
        args: ["--config", "pyproject.toml"]
